# Generated by Django 6.0 on 2025-12-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_id',
            field=models.IntegerField(),
        ),
    ]
